CC = gcc

all:
	$(CC) planoInclinado.c -o plano -lGL -lSDL -lglut
	$(CC) vector.c -o vector -lGL -lSDL -lglut
	$(CC) vector3D.c -o 3d -lGL -lSDL -lglut
plano:
	$(CC) planoInclinado.c -o plano -lGL -lSDL -lglut
vector2d:
	$(CC) vector.c -o vector -lGL -lSDL -lglut
vector3d:
	$(CC) vector3D.c -o 3d -lGL -lSDL -lglut